### ISSUE TITLE
Difficulty reproducing results

### ISSUE THREAD

**Issue by crixus5678** [sharathadavanne/seld-dcase2022#1]
Hi, 

I'm wondering if anyone tried to reproduce the results? I tried to run setting 3 and the F1-score was at 0.14 (average of 5 trials). I'm wondering is it because I trained it without the synthetic set (DCASE 2022 simulated data for baseline training - https://doi.org/10.5281/zenodo.6406873) that's why that is quite a big gap with the reported accuracy

Best Regards,

**Comment by sharathadavanne** [comment]
Hey @crixus5678 you are right, the results we have reported as baseline scores were obtained by training on a mixture of synthetic and real-life data, and testing it on real-life data only.

**Comment by crixus5678** [comment]
@sharathadavanne thanks for the fast reply. Let me try it again
