### ISSUE TITLE
It seems there some issues in SELD_evaluation_metrics.py

### ISSUE THREAD

**Issue by Jinbo-Hu** [sharathadavanne/seld-dcase2022#2]
Hi,
It seems there are some issues in SELD_evaluation_metrics.py.
Line 137:  `gt_doas = gt_arr[:, :-1]` and Line 141 `pred_doas = pred_arr[:, :-1]`.
It seems that `gt_arr[:, 0]` and `pred_arr[:, 0]` are source number indexes, rather than `gt_arr[:, -1]` and `pred_arr[:, -1]`.

**Comment by sharathadavanne** [comment]
Thanks for participating in the challenge @Jinbo-Hu 

The variables `gt_arr` and `pred_arr` are of the form [azimuth_angle_degrees, elevation_angle_degrees, track_id]
So using `gt_arr[:, :-1]` and  `pred_arr[:, :-1]` should ideally give us [azimuth_angle_degrees, elevation_angle_degrees]
I checked it again on my end. Could you verify the same from your side?

**Comment by Jinbo-Hu** [comment]
Thanks for your quick response!

I run your baseline code.
Here is one of outputs of `gt_arr`, `gt_doas`, `pred_arr`, `pred_doas`
> `gt_arr:  [[  1.  35. -12.]]`
`gt_doas:  [[ 1. 35.]]`
`pred_arr:  [[   0.         -101.32076171  -15.99277551]]`
`pred_doas:  [[   0.         -101.32076171]]`

It still seems that `gt_arr[:, 0]` and `pred_arr[:, 0]` are source number indexes.

**Comment by sharathadavanne** [comment]
You were right @Jinbo-Hu Thanks for spotting the bug. We have now fixed the code.
[Check this commit](https://github.com/sharathadavanne/seld-dcase2022/commit/b64091d8c271159c75b207df71ff41f6c217c9b8) to see the difference in the `SELD_evaluation_metrics.py` file
